FROM ubuntu:latest

RUN apt-get update && apt-get install -y curl

RUN curl https://get.modular.com | MODULAR_AUTH=mut_a26acd39cfa2437fa0f4a7fe51627495 sh -

RUN modular install mojo

RUN echo 'export MODULAR_HOME="$HOME/.modular"' >> ~/.bashrc && \
    echo 'export PATH="$MODULAR_HOME/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.bashrc


CMD ["/bin/bash"]
